spring.application.name=TorqueDesk

spring.datasource.url=jdbc:postgresql://localhost:5432/torquedesk_db
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evitar problemas com doker na fase inicial #
spring.docker.compose.enabled=false

jwt.secretKey=7vD8mQ3PzLkN9xW4sH2rY5uJ8cT1fB6aR0nM7pQ2vX9zK5wE
jwt.identityExpiration=900
jwt.workspaceExpiration=3600
security.jwt.refresh-expiration=2592000